### ISSUE TITLE
does the project still support RDP traffic capture

### ISSUE THREAD

**Issue by gemone** [Devolutions/devolutions-gateway#290]
Hi!

Thanks for your job!

`README` says that `A blazing fast relay server adaptable to different protocols and desired levels of traffic inspection.`

I see the content related to RDP in the source code annotation. 

Is there any plan to continue developing for RDP traffic? And The document description is not clear. Can I use the command line to establish a gateway caputres the RDP traffic? Can I get some example?

Thanks!

**Comment by awakecoding** [comment]
Short answer: no

Long answer: we sort of had a way to do it, but it's complicated and required setting two passwords in the gateway such that RDP NLA could be performed once on both sides with NTLM, and then relay the traffic. It's very limiting and difficult to work with for production use, so we never shipped it, but code should still be there. I'm just not sure about its current functional state though.

We do wish to get RDP traffic capture working, and you've come to the right place for it, the issue is that RDP NLA is very hostile to TLS inspection by a proxy because it uses two different forms of channel binding. That's why authenticating twice works, because the client authenticates against the first TLS hop thinking it is the destination server.

I have some ideas on how to redesign the protocol connection sequence but trying to hook that into the official Microsoft RDP client would require a fair amount of work. In the meantime, I suggest you try our other project that extends the Microsoft RDP client, MsRdpEx, with API hooking, including an experimental feature to dump a decrypted pcap file: https://github.com/Devolutions/MsRdpEx#wireshark-packet-capture

Let me know if client-side traffic capture from the RDP client suits your needs.

**Comment by gemone** [comment]
@awakecoding Sorry for the late reply.

`client-side traffic capture from the RDP client` seems that it is not widely used. 

As a user, it seems that he does not record his behavior when operating the remote desktop. However, as a service provider, it is more desirable to keep the user's operation records. 

I try to capture the RDP traffic of the Internet users when they use the intranet machines. At present, there seems to be no good solution. 

> And `proxy` seems to be a good solution, but its performance is poor.

**Comment by awakecoding** [comment]
"I try to capture the RDP traffic of the Internet users when they use the intranet machines. At present, there seems to be no good solution."

Now I understand what you are trying to do, and I can say with absolute certainty that you won't find anything that does this at the proxy-level for RDP connections without downgrading security. The protocol itself is very hostile to protocol inspection, and we've been trying to figure out ways around it that wouldn't degrade the security. All I can really offer are pointers if you are looking to develop the thing yourself, there is no tool or product available that does this.

**Comment by EthanHeilman** [comment]
@awakecoding's anwer makes it sound like this is unsupported in gateway, but [this video](https://youtu.be/paw_cyY8BoQ?feature=shared&t=2854) shows gateway doing remote RDP session recording. 

Is it that gateway can only record videos, not the underlying traffic?

**Comment by CBenoit** [comment]
Hi @EthanHeilman 

Actually, the video you linked is not showcasing proxy-based RDP session recording.
Our current solution is to let the client itself records the session and stream the resulting webm stream to the Devolutions Gateway.
Devolutions Gateway is able to shut down the session if the recording stream is stopped (this behavior is based on the recording policy encoded at the token-level), but it’s definitely possible for a careful attacker to intercept the network packets and replace them with garbage before they reach the Devolutions Gateway, in which case the Devolutions Gateway will happily continue forwarding the session stream to the target server.

Since 2022, we made great progress towards proxy-based recording, but it’s still not an easy problem to solve for the very same reasons @awakecoding mentioned in his answer above.

The progress we made:

- Our Rust implementation of the RDP protocol, [IronRDP](https://github.com/Devolutions/IronRDP), got much more mature and reliable, and we are using it today for building a web client using the WebAssembly target. We are absolutely in good position to use that directly inside the proxy, and to decode and record the video directly there. We also get to see the other interesting interactions at the protocol-level that can’t be seen in video (such as key presses outside of a visible text field).

- Devolutions Gateway now embeds our media toolkit, [Cadeau](https://github.com/Devolutions/cadeau) for efficient webm video processing. This is what we are using in RDM for generating the webm recording stream too. (Currently we only use it for remuxing the webm files streamed by the client.)

The remaining major roadblock is that we basically need to perform a form of MITM-attack, which is prevented by TLS security model used in modern RDP. Working around this still requires degrading the security, or alternatively, an intrusive modification at the client level.

For the latter, we actually implemented [a small extension to the RDP protocol](https://github.com/Devolutions/devolutions-gateway/blob/32de1d50de509559e2b8f2d6c7e1259c0db85cb1/devolutions-gateway/src/rdp_extension.rs) allowing the Devolutions Gateway to inspect the whole traffic. This is currently only used by the web client. The idea is that we perform TLS between the client and the Devolutions Gateway, and between the Devolutions Gateway and the server, but we still send the server’s certificate to the RDP client for ensuring that the final target is the one it expects.

The real challenge is to make these intrusive modifications in Microsoft’s client, mstsc. This requires reverse engineering stuff and hooking a DLL using [Detours](https://github.com/microsoft/Detours) to hijack some strategical function. This approach is also fragile and may require regular maintenance as Microsoft will keep updating their client and may break our code.

We can actually support that relatively easily when IronRDP is used as the client: we provide both a native client in RDM, and a web client in Devolutions Server / Devolutions Hub / Devolutions Gateway Standalone; but most of our customers are using the built-in Microsoft client which is much more featureful that ours. We also don’t receive many feature requests for actual proxy-based recording, so this project is not a priority, and we end up moving baby-step by baby-step depending on our bandwidth.

If you want to voice your interest for this feature, the best place for that is [our official forum](https://forum.devolutions.net/).

**Comment by EthanHeilman** [comment]
> For the latter, we actually implemented [a small extension to the RDP protocol](https://github.com/Devolutions/devolutions-gateway/blob/32de1d50de509559e2b8f2d6c7e1259c0db85cb1/devolutions-gateway/src/rdp_extension.rs) allowing the Devolutions Gateway to inspect the whole traffic. This is currently only used by the web client. The idea is that we perform TLS between the client and the Devolutions Gateway, and between the Devolutions Gateway and the server, but we still send the server’s certificate to the RDP client for ensuring that the final target is the one it expects.

That's impressive. I figured you'd just do something like change the target domain name `windowsmachine123.example.com` to a devolutions controlled domain `windowsmachine-dot-example-dot-com.mitm.devolutions.com` behind the scenes in the web-client and then check the destination target domain TLS cert in the proxy and not worry about sending the server's certificate to the RDP client. What checks does  the RDP client do on the cert?

If you aren't terminating the client-based TLS session in Devolutions Gateway, how do you inject passwords and credentials via PAM?

**Comment by awakecoding** [comment]
> If you aren't terminating the client-based TLS session in Devolutions Gateway, how do you inject passwords and credentials via PAM?

The credentials are simply injected in the RDP client, we don't inject them at the proxy level. Since they're PAM credentials, they are obviously changed after consumption.

**Comment by CBenoit** [comment]
> What checks does the RDP client do on the cert?

I think at this point we are not checking the certificate validity, and we only extract the public key for performing CredSSP. It would be best to perform the usual checks and show a pop-up to the user if something is wrong, like in mstsc. The problem here is that it’s not so simple to perform the full certificate validation, I don’t think browsers provide an API for that, and for instance, we don’t have access to the system certificate store. You would get an error if you used a custom certification authority. I’m thinking the best we could do is to let Devolutions Gateway performs the validation and returns a status code to the client instead, but we didn’t analyzed the question to the full extent yet.
