### ISSUE TITLE
Spurious subject name mismatch warning when using a wildcard certificate

### ISSUE THREAD

**Issue by Necrotyr** [Devolutions/devolutions-gateway#634]
Hello,

When trying to use the Windows certificate store the gateway will not work when specifying a wildcard cert.

gateway.json looks like this:
```
{
  "Id": "<redacted>",
  "Hostname": "gateway.example.com",
  "ProvisionerPublicKeyFile": "provisioner.pem",
  "TlsCertificateSource": "System",
  "TlsCertificateSubjectName": "*.example.com",
  "TlsCertificateStoreLocation": "LocalMachine",
  "Listeners": [
    {
      "InternalUrl": "https://*:7171",
      "ExternalUrl": "https://*:7171"
    },
    {
      "InternalUrl": "tcp://*:8181",
      "ExternalUrl": "tcp://*:8181"
    }
  ]
}
```

The gateway log has this after restarting the service:
> 2024-01-09T11:28:18.580181Z  INFO devolutions_gateway::service: version="2023.3.0"
> 2024-01-09T11:28:18.580295Z  INFO devolutions_gateway: devolutions-gateway service started
> 2024-01-09T11:28:18.580300Z  INFO devolutions_gateway: args: ["DevolutionsGateway"]
> 2024-01-09T11:28:18.580664Z  INFO devolutions_gateway::service: Reading JRL file from disk (path: C:\ProgramData\Devolutions\Gateway\jrl.json)
> 2024-01-09T11:28:18.580851Z  INFO devolutions_gateway::listener: Initiating listener… url=https://[::]:7171/
> 2024-01-09T11:28:18.581403Z  INFO devolutions_gateway::listener: Listener started successfully kind=Https addr=[::]:7171
> 2024-01-09T11:28:18.581447Z  INFO devolutions_gateway::listener: Initiating listener… url=https://0.0.0.0:7171/
> 2024-01-09T11:28:18.581549Z  INFO devolutions_gateway::listener: Listener started successfully kind=Https addr=0.0.0.0:7171
> 2024-01-09T11:28:18.581556Z  INFO devolutions_gateway::listener: Initiating listener… url=tcp://[::]:8181
> 2024-01-09T11:28:18.581642Z  INFO devolutions_gateway::listener: Listener started successfully kind=Tcp addr=[::]:8181
> 2024-01-09T11:28:18.581665Z  INFO devolutions_gateway::listener: Initiating listener… url=tcp://0.0.0.0:8181
> 2024-01-09T11:28:18.581741Z  INFO devolutions_gateway::listener: Listener started successfully kind=Tcp addr=0.0.0.0:8181
> 2024-01-09T11:29:39.850012Z  WARN listener{port=7171}:https{client=<ip redacted>:64774}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"
> 2024-01-09T11:29:54.874337Z  WARN listener{port=7171}:https{client=<ip redacted>:64774}: devolutions_gateway::listener: request timed out error=deadline has elapsed
> 2024-01-09T11:30:50.688480Z  WARN listener{port=7171}:https{client=<ip redacted>:64840}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"
> 2024-01-09T11:31:05.697058Z  WARN listener{port=7171}:https{client=<ip redacted>:64840}: devolutions_gateway::listener: request timed out error=deadline has elapsed
> 2024-01-09T11:31:05.697254Z  WARN listener{port=7171}:https{client=<ip redacted>:64852}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"
> 2024-01-09T11:31:05.708413Z  INFO listener{port=7171}:https{client=<ip redacted>:64852}:request{method=GET path=/jet/diagnostics/clock}: devolutions_gateway::middleware::log: duration=236.4µs status=200 OK
> 2024-01-09T11:31:05.756644Z  WARN listener{port=7171}:https{client=<ip redacted>:64855}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"
> 2024-01-09T11:31:05.784417Z  WARN listener{port=7171}:https{client=<ip redacted>:64856}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"
> 2024-01-09T11:31:05.790703Z  INFO listener{port=7171}:https{client=<ip redacted>:64856}:request{method=GET path=/jet/diagnostics/configuration}: devolutions_gateway::middleware::log: duration=571.9µs status=200 OK

If I replace *.example.com in TlsCertificateSubjectName with the full servername (gateway.example.com) the log throws this error instead, which is to be expected:
> 2024-01-09T11:45:09.940440Z ERROR listener{port=7171}:https{client=10.1.137.11:64976}: devolutions_gateway::listener: handle_https_peer failed error="TLS handshake failed: unexpected error: no server certificate chain resolved"

**Comment by Necrotyr** [comment]
Short update; After manually adding the intermediate certificate to the gateway server it's now possible to connect, though the log still throws these warnings:
> 2024-01-09T11:55:46.025653Z  WARN listener{port=7272}:https{client=<ip redacted>:65027}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"

**Comment by CBenoit** [comment]
Hi! Thank you for opening this issue.

> Short update; After manually adding the intermediate certificate to the gateway server it's now possible to connect, though the log still throws these warnings:
> 
> > 2024-01-09T11:55:46.025653Z  WARN listener{port=7272}:https{client=:65027}: devolutions_gateway::tls::windows: Subject name mismatch request_server_name="gateway.example.com" expected_server_name="*.example.com"

I see! Yes, actually the intermediate certificate is also required on the server, i.e., both the leaf and the intermediate (the full certification chain excluding the root CA).

There is a catch however. It’s technically not required if the client application is able to find the intermediate certificate by itself (e.g.: Firefox). However, most applications (curl, RDM, DVLS…) are not able to do that, and will refuse to connect to the server (Devolutions Gateway). Firefox is making a best effort thing, but that’s not considered a proper configuration.

Unfortunately, some popular CAs such as GoDaddy are not bundling the intermediate certificate along the leaf certificate, and IT admins must handle that by themselves, and this typically creates churn.

Here is one of the many occurrences: https://forum.devolutions.net/topics/40774/devolutions-gateway-not-working-for-websites

This applies when using the file system as a certificate source, but also when using the Windows certificate store, as you experienced.
Adding the intermediate certificate into the Windows certificate store on the machine running the Devolutions Gateway is the appropriate solution, and once added to the intermediate certificate store, Devolutions Gateway will automatically start sending it along the leaf certificate (no reboot required).

We have a ticket internally to update the knowledge base with troubleshooting steps and other relevant information.

I put the bug label on this issue because the warning should not be issued if the domain matches is matched by the wildcard name.

**Comment by Necrotyr** [comment]
Hi Benoît,

Thanks for the update.

To be honest I didn't even think about the intermediate at first, because it's usually included with globalsign certificates, but when i tried to look at the chain in the cert store it couldn't validate it, as the server was not allowed to connect til OCSP/CRL, once I imported it manually it started working, we've also allowed access to OCSP and CRL afterwards.

We'll ignore the certificate warnings in the log, I'll look out for a new version whenever you release one :-)

Best regards,

**Comment by CBenoit** [comment]
Hi @Necrotyr!

A new build including the fix is available: https://github.com/Devolutions/devolutions-gateway/releases/tag/v2024.1.1 

This build didn’t went through [the full testing process](https://github.com/Devolutions/devolutions-gateway?tab=readme-ov-file#from-github), but unless you are interested into the new standalone feature it’s not very relevant.
Otherwise, we are planning on having it published on the website through the next week.
